In [1]:
import numpy as np

In [5]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
a.shape

(2, 2, 3)

In [7]:
a[1,0,2]

9

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [21]:
from math import *

In [12]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)

[5 7 9]
[ 4 10 18]


In [17]:
a = np.array([1, 2, 3])

# Add a scalar to an array
print(a + 2)

# Multiply every element by a scalar
print(a * 2)

[3 4 5]
[2 4 6]


In [20]:
a = np.array([1, 2, 3]).reshape(3,1)
b = np.array([4, 5, 6]).reshape(1,3)
print(a)
print(b)
print(a * b)

[[1]
 [2]
 [3]]
[[4 5 6]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [22]:
a = np.array([1, 2, 3])

# Square root
print(np.sqrt(a))

# Exponential
print(np.exp(a))

# Sin function
print(np.sin(a))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


In [24]:
a = np.array([1, 3, 2])

# Sum
print(np.sum(a))

# Mean
print(np.mean(a))

# Max
print(np.max(a))

# Sorting
print(np.sort(a))

6
2.0
3
[1 2 3]


In [25]:
a = np.array([1, 2, 3])

# Slicing
print(a[0:2])  # Get the first two elements

# Boolean indexing
print(a[a > 2])  # Get elements greater than 2

# Fancy indexing
indices = [1, 2]
print(a[indices])  # Get elements at index 1 and 2

[1 2]
[3]
[2 3]


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose
print(a.T)

# Reshape
print(a.reshape(3, 2))

# Flatten
print(a.flatten())

[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [31]:
a = np.array([[1, 2, 3], [4,5,6]])
print(a[:, 0:2])

[[1 2]
 [4 5]]
