In [1]:
import numpy as np

In [9]:
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([[1,3,5], [7,9,11]])
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)
print(arr1.ndim)
print(arr2.ndim)
print(arr1.dtype)
print(arr2.dtype)

[ 2  4  6  8 10]
[[ 1  3  5]
 [ 7  9 11]]
(5,)
(2, 3)
1
2
int64
int64


In [8]:
print(arr1 + 5)
print(arr1 - 5)
print(arr1 * 5)
print(arr1 / 5)
print(arr1 // 5)
print(arr1 % 5)
print(arr1 ** 5)
print(arr2 * 3)

[ 7  9 11 13 15]
[-3 -1  1  3  5]
[10 20 30 40 50]
[0.4 0.8 1.2 1.6 2. ]
[0 0 1 1 2]
[2 4 1 3 0]
[    32   1024   7776  32768 100000]
[[ 3  9 15]
 [21 27 33]]


In [14]:
print(arr1[0:2])
print(arr2[1: ])
indices = [1, 3]
print(arr1[indices])

[2 4]
[[ 7  9 11]]
[4 8]


In [15]:
import math as m
print(arr1 + 3)
print(np.sqrt(arr1))
print(np.sin(arr1))

[ 5  7  9 11 13]
[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]


In [16]:
arr3 = np.array([12, 14, 16, 18, 20])
print(np.vstack((arr1, arr3)))
print(np.hstack((arr1, arr3)))

[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[ 2  4  6  8 10 12 14 16 18 20]


In [19]:
arr4 = np.array([[13,15],[17,19]])
print(np.concatenate((arr2, arr4), axis=1))

[[ 1  3  5 13 15]
 [ 7  9 11 17 19]]


In [24]:
print(arr1 > 6)
mask = arr1 > 6
print(arr1[mask])

[False False False  True  True]
[ 8 10]


In [25]:
print(arr1.reshape(5,1))


[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [26]:
arr2_transposed = np.transpose(arr2)
print(arr2_transposed)

[[ 1  7]
 [ 3  9]
 [ 5 11]]
